In [1]:
import pandas as pd
import requests
import bs4
import pickle
import numpy as np
import re
import codecs

In [2]:
df=pd.read_csv('urls.csv')

In [7]:
df.shape

(1097, 2)

In [3]:
df

      Unnamed: 0                                               urls
0              0  https://www.quikr.com/electronics-appliances/a...
1              1  https://www.quikr.com/electronics-appliances/g...
2              2  https://www.quikr.com/electronics-appliances/b...
3              3  https://www.quikr.com/electronics-appliances/a...
4              4  https://www.quikr.com/electronics-appliances/a...
...          ...                                                ...
1092        1092  https://www.quikr.com/electronics-appliances/l...
1093        1093  https://www.quikr.com/electronics-appliances/8...
1094        1094  https://www.quikr.com/electronics-appliances/d...
1095        1095  https://www.quikr.com/electronics-appliances/l...
1096        1096  https://www.quikr.com/electronics-appliances/i...

[1097 rows x 2 columns]

In [4]:
print(df['urls'].iloc[1])

https://www.quikr.com/electronics-appliances/good-fujitsu-laptop-available-for-cheap+delhi+W0QQAdIdZ338899746

In [5]:
prices=[]
description=[]
condition=[]
for i in range(df.shape[0]):
    try:      
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
        src = requests.get(df['urls'].iloc[i], headers=headers)
        soup = bs4.BeautifulSoup(src.text, 'html.parser')
        
        var=soup.find('div', class_='hidden-xs displayArrange')
        try:
            prices.append(var.find('span').text.strip())
        except:
            prices.append(np.nan)
        var2=soup.find('div', class_='productdetailsdata')
        try:
            var3=var2.find('div', class_='expandArea')
            condition.append(var3.find('span').text.strip())
        except:
            condition.append(np.nan)
        try:
            description.append(var2.find('div', class_='descriptionText').text.strip())
        except:
            description.append(np.nan)
    except:
        pass

store=[]
for i in range(df.shape[0]):
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
        src = requests.get(df['urls'].iloc[i], headers=headers)
        soup = bs4.BeautifulSoup(src.text, 'html.parser') 
        
        var2=soup.find('div', class_='productdetailsdata')
        var4=var2.find('div', class_='expandArea2')
        store.append(var4.find_all('span'))
    except:
        store.append(np.nan)
        
brand=[]
screen_size=[]
ram=[]
model=[]
product_type=[]
for i in range(len(store)):
    try:
        brand.append(store[i][0].text.strip())
    except:
        brand.append(np.nan)
    try:
        product_type.append(store[i][2].text.strip())
    except:
        product_type.append(np.nan)
    try:
        screen_size.append(store[i][3].text.split(' ')[2])
    except:
        screen_size.append(np.nan)
    try:
        ram.append(store[i][4].text.strip())
    except:
        ram.append(np.nan)
    try:
        model.append(store[i][6].text.strip())
    except:
        model.append(np.nan)

In [6]:
print(len(prices))
print(len(condition))
print(len(description))
print(len(brand))
print(len(screen_size))
print(len(ram))
print(len(model))
print(len(product_type))

1097
1097
1097
1097
1097
1097
1097
1097

In [9]:
d={'brand':brand,'condition':condition,'product_type':product_type,'model':model,'ram':ram,'screen_size':screen_size,'prices':prices
  ,'description':description}
data=pd.DataFrame(d)

In [10]:
data

,brand,condition,product_type,model,ram,screen_size,prices,description
0,Asus,Brand New,Laptop,Asus X507UF-EJ101T,8GB,15.9,"â‚¹\n 35,000",Model - Asus X507UF-EJ101T\nRAM - 8GB\nGraphic...
1,Fujitsu,Gently Used,Laptop,AH 502 NG,2GB,15.9,"â‚¹\n 6,000",Good Fujitsu laptop available for cheap
2,HP ( Hewlett-Packard),Brand New,Laptop,NaN,4GB,15.9,"â‚¹\n 35,500","perfect for online classes- student, 2.1GHz In..."
3,Apple,Heavily Used,Laptop,NaN,NaN,NaN,"â‚¹\n 82,000",Dimension : W * D * H 3 x 3 x 3 cm (1 x 1 x 1 ...
4,Apple,Gently Used,Laptop,NaN,NaN,NaN,"â‚¹\n 75,999",Dimension : W * D * H 3 x 3 x 3 cm (1 x 1 x 1 ...
...,...,...,...,...,...,...,...,...
1092,Dell,Gently Used,Laptop,INSPIRON,4GB,14.9,"â‚¹\n 11,599","256GB STORAGE, 64BIT i5 3rd Gen ,windows 10 ,o..."
1093,HP ( Hewlett-Packard),Almost Like New,Laptop,NaN,NaN,NaN,"â‚¹\n 15,000",8470 elitebook i5 3rd Gen HP ( Hewlett-Packar...
1094,Dell,Almost Like New,Laptop,NaN,NaN,NaN,"â‚¹\n 20,000",
1095,Lenovo,Gently Used,Laptop,NaN,NaN,NaN,"â‚¹\n 3,000",
1096,Acer,Gently Used,Laptop,"Acer 4740 series ,modal ms-2308",2GB,15.9,"â‚¹\n 10,501",In good condition laptop laptop inbild mic Wab...

In [11]:
data.to_csv('laptop_data.csv')